#!/usr/bin/env bash
set-hook -g client-focus-out[0] 'run-shell "#{@METAPHILEROOT}/metaphile.tmux" \; refresh-client' 
set-hook -g client-focus-in[0] 'run-shell "#{@METAPHILEROOT}/metaphile.tmux" \; refresh-client'
set-hook -g pane-focus-in[0] 'run-shell "#{@METAPHILEROOT}/metaphile.tmux" \; refresh-client' 
set-hook -g pane-exited[0] 'run-shell "#{@METAPHILEROOT}/metaphile.tmux" \; refresh-client'
set-hook -g session-window-changed[0] 'run-shell "#{@METAPHILEROOT}/metaphile.tmux" \; refresh-client'
