#!/usr/bin/env bash
main() 
{
  local script="$( tmux show -gqv @MF_ROOT )/scripts/metaphile.sh"
  tmux set-hook -g client-focus-out[0] 'run-shell "#{@MF_ROOT}/scripts/metaphile.sh \; refresh-client"' 
  tmux set-hook -g client-focus-in[0] 'run-shell "$script \; refresh-client"'
  tmux set-hook -g pane-focus-in[0] 'run-shell "$script \; refresh-client"' 
  tmux set-hook -g pane-exited[0] 'run-shell "$script \; refresh-client"'
  tmux set-hook -g session-window-changed[0] 'run-shell "$script \; refresh-client"'
}
main 
